=== joaocarloscardoso/knaorec_ws_client/data/PortfolioSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2013 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="portfolio">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="audits">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="Audit" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="About">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="version" maxOccurs="unbounded">
														<xs:complexType>
															<xs:attribute ref="id" use="required"/>
															<xs:attribute ref="rem">
																<xs:annotation>
																	<xs:documentation>remarks, additional comments, eg. stage of followu-up</xs:documentation>
																</xs:annotation>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
													<xs:element name="title">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="tx" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:attribute ref="l" use="required"/>
																		<xs:attribute ref="nm" use="required"/>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="WorkingLanguage">
														<xs:annotation>
															<xs:documentation>TBD</xs:documentation>
														</xs:annotation>
														<xs:complexType>
															<xs:attribute ref="wl" use="required">
																<xs:annotation>
																	<xs:documentation>TBD: wl or l</xs:documentation>
																</xs:annotation>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute ref="id" use="required"/>
												<xs:attribute name="descriptionfile" type="xs:token">
													<xs:annotation>
														<xs:documentation>TBD</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="yearCovered" type="xs:token">
													<xs:annotation>
														<xs:documentation>TDB</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="casesNumber" type="xs:long">
													<xs:annotation>
														<xs:documentation>autocalc</xs:documentation>
													</xs:annotation>
												</xs:attribute>
												<xs:attribute name="date" type="xs:string"/>
												<xs:attribute ref="rem"/>
											</xs:complexType>
										</xs:element>
										<xs:element name="Background">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="ak" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Scope">
											<xs:complexType>
												<xs:sequence>
													<xs:element ref="ak" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Cases">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Case" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="cts">
																	<xs:complexType>
																		<xs:attribute name="issue" type="xs:token" use="required"/>
																		<xs:attribute name="area" type="xs:token" use="required"/>
																		<xs:attribute name="domain" type="xs:token" use="required"/>
																		<xs:attribute name="source" type="xs:token" use="required"/>
																	</xs:complexType>
																</xs:element>
																<xs:element ref="quote" maxOccurs="unbounded"/>
															</xs:sequence>
															<xs:attribute name="number">
																<xs:annotation>
																	<xs:documentation>TBD</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute ref="nr" use="required"/>
															<xs:attribute ref="nm" use="required"/>
															<xs:attribute name="eff" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="doc" use="required">
																<xs:annotation>
																	<xs:documentation>reference to other location in this doc</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="act" use="required">
																<xs:annotation>
																	<xs:documentation>reference to a relevant legal act</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="Include">
																<xs:annotation>
																	<xs:documentation>TBD</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="Recommendations">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="Recommendation" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element ref="quote" maxOccurs="unbounded"/>
																<xs:element name="findings" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence minOccurs="0">
																			<xs:element name="finding" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:attribute ref="nr"/>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="monitoring" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence minOccurs="0">
																			<xs:element name="assessment" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:attribute name="status" use="required">
																						<xs:simpleType>
																							<xs:restriction base="xs:string"/>
																						</xs:simpleType>
																					</xs:attribute>
																					<xs:attribute ref="nr"/>
																					<xs:attribute name="note" use="required">
																						<xs:simpleType>
																							<xs:restriction base="xs:string"/>
																						</xs:simpleType>
																					</xs:attribute>
																					<xs:attribute name="date" use="required">
																						<xs:simpleType>
																							<xs:restriction base="xs:string"/>
																						</xs:simpleType>
																					</xs:attribute>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
															<xs:attribute name="riskevaluation" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="risk" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="repeated" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="priority" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="number">
																<xs:annotation>
																	<xs:documentation>TBD</xs:documentation>
																</xs:annotation>
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="nr" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="importance" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="category" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
															<xs:attribute name="accepted" use="required">
																<xs:simpleType>
																	<xs:restriction base="xs:string"/>
																</xs:simpleType>
															</xs:attribute>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="title">
										<xs:annotation>
											<xs:documentation>TBD</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value=""/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="order">
										<xs:annotation>
											<xs:documentation>TBD</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value=""/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
									<xs:attribute name="id">
										<xs:annotation>
											<xs:documentation>TBD</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value=""/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="publish" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="org" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="id" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="description" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name="coverage" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string"/>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="id" type="xs:token"/>
	<xs:attribute name="rem">
		<xs:annotation>
			<xs:documentation>remarks, additional comments</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="l" type="xs:token">
		<xs:annotation>
			<xs:documentation>language</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:attribute name="wl">
		<xs:annotation>
			<xs:documentation>working language</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:element name="ak">
		<xs:annotation>
			<xs:documentation>paragraph - open for rich content</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="true">
			<xs:attribute ref="l"/>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="name"/>
	<xs:attribute name="nm" type="xs:normalizedString">
		<xs:annotation>
			<xs:documentation>name</xs:documentation>
		</xs:annotation>
	</xs:attribute>
	<xs:element name="quote">
		<xs:complexType mixed="true">
			<xs:attribute ref="l"/>
			<xs:attribute name="type" type="xs:normalizedString">
				<xs:annotation>
					<xs:documentation>Can be e.g. a description, or reference to previous recommendation</xs:documentation>
				</xs:annotation>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:attribute name="nr" type="xs:token"/>
</xs:schema>

=== joaocarloscardoso/knaorec_ws_client/data/Portfolio01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- output sample to be generated by application -->
<portfolio id="DepartmentAuditingPerformance_2020" description="AAG Vlora Spanca: Auditing of Performance and Procurement" coverage="year 2020" org="National Audit Office of Kosovo" publish="1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="PortfolioSchema.xsd">
	<audits>
		<Audit>
			<About id="ATK-SIGTAS" descriptionfile="" year="2020" month="01">
				<version id="1.0"/> 
				<title>
					<tx l="eng" nm="Tax administration" /> 
				</title>
				<WorkingLanguage wl="eng"/>
			</About>
			<Background>
				<ak>Background</ak>
			</Background>
			<Scope>
				<ak/>
			</Scope>
			<Cases>
				<Case nr="F20200513-160001" nm="In the TAK information system there are shortcomings in controls of error handling" eff="The lack of error messages for each level of field or transaction, and lack of procedures for identifying errors and correcting them before processing, poses the risk that errors are not avoided and results in the constant increase of error rates. Meanwhile, the lack of interconnection of tax return statements between the systems and non-harmonization of data across systems, results with an incomplete presentation of taxpayers’ statement as well as the inability of the TAK to have an accurate report of tax revenues." act="" doc="" Include="Yes" number="1">
					<cts source="AITAM" domain="07 Application Controls" area="01 Input Controls" issue="03 Adequate procedures for error handling"/>
					<quote type="description">Entry control procedures must ensure that every transaction that will be processed has been entered, processed and recorded completely and accurately. The information system should have clear validity checks for error handling by communicating problems. Errors that occur when placing data in the relevant fields can be tracked and corrected before processing transactions. Error recordings should be reviewed periodically, and the necessary corrective actions should be undertaken.</quote>
					
				</Case>
				<Case nr="F20200513-160145" nm="The calculation of the penalty on an interest rate in advance installments is not complete and accurate." eff="Failure to fully and accurately calculate the penalty in the installment results in taxpayers paying more penalty in the installment than required, and in the other case, it affects TAK with not collecting its revenues." act="" doc="" Include="Yes" number="2">
					<cts source="AITAM" domain="07 Application Controls" area="02 Processing Controls" issue="02 Application controls"/>
					<quote type="description">The application must have established procedures to ensure that the assessment of the completeness and accuracy of the applications’ results is carried out and that the same can be further processed or proceeded according to the pre-defined criteria.</quote>

				</Case>
				<Case nr="F20200513-160231" nm="The data on the assessments of tax returns statements are not accurate in the agreements for payment of tax debts in installments" eff="Inaccurate calculation of the penalty accumulated during the agreement affect the taxpayer by obliging them to pay more of the penalty than required. Also, the incorrect presentation of the calculation of tax liability data in the reports, results with the incorrect presentation of tax statements." act="" doc="" Include="Yes" number="3">
					<cts source="AITAM" domain="07 Application Controls" area="02 Processing Controls" issue="02 Application controls"/>
					<quote type="description">The organization should have control procedures to ensure that transaction data in information systems are harmonized. The output reports must be complete and provide accurate representation of the data source.</quote>
					
				</Case>
				<Case nr="F20200513-160339" nm="Tax payments made through e-banking after 17:00, are registered in TAK as payments made one day later" eff="Due to the absence of payment order's date in TAK registry, the date when the payment was executed, TAK registers the date of payment the day the banking transaction was realized and as a result the taxpayers are harmed. Furthermore, the taxpayer, although he paid the tax liability within the time limit, has been penalized with administrative penalty and interest." act="" doc="" Include="Yes" number="4">
					<cts source="AITAM" domain="07 Application Controls" area="02 Processing Controls" issue="02 Application controls"/>
					<quote type="description">The payment system must provide the necessary information in the messages of sending/receiving financial payment transactions, including the date and time of the transaction.   The payment of Tax liabilities must be realized within the set time limit. If any amount of any tax administered by TAK under applicable law in Kosovo has not been paid by the deadline set for payment, the taxpayer will be obliged to pay interest fee  and will be subjected to an administrative penalty of one percent (1%) of the tax liability.</quote>
					<!--<quote type="recommendation"/>-->
				</Case>
				<Case nr="F20200513-160501" nm="The SIGTAS system contains errors in the configuration of debt forgiveness transactions and tax refunds, appearing as an overpayment /credit in the taxpayer's tax statement." eff="Inadequate system configuration for tax debt forgiveness and tax refund cases risks that the taxpayers seek to be reimbursed for the overpayments/credits that appear in the tax account statement, even though they have not made that payment. This harms TAK financially leading to possible double transactions." act="" doc="" Include="Yes" number="5">
					<cts source="AITAM" domain="07 Application Controls" area="02 Processing Controls" issue="02 Application controls"/>
					<quote type="description">The application must have validity control procedures to protect it against errors in transaction processing. They must be configured to ensure that application transactions are executed in accordance with the expected performance.</quote>
					<!--<quote type="recommendation"/>-->
				</Case>
				<Case nr="F20200513-160605" nm="TAK penalizes the taxpayer who is subjected to taxation on the basis of real income with administrative penalty of non-payment of tax less than 0.01€" eff="Failure to make a decision on how to handle these cases of differences (with less than € 0.01), even if the taxpayer has complied with the time limit and the amount to be paid, financially harms the taxpayer, punishing him with a penalty in installment of the full tax liability." act="" doc="" Include="Yes" number="6">
					<cts source="AITAM" domain="07 Application Controls" area="03 Output Controls" issue="01 Assessment of application"/>
					<quote type="description">The organization should define clearly the processes of the output of transaction results and the correct documentation of the report extraction logic  in the application. If the advance payment has not been done accurately and in a timely manner, TAK applies a penalty in an amount equal to the interest rate in force at a time when the advance payment is obliged.</quote>
					<!--<quote type="recommendation"/>-->
				</Case>
				<Case nr="F20200513-160706" nm="TAK treats the remaining tax debt of three (3) euros or less as a paid value" eff="TAK suffered a loss of tax revenues." act="" doc="" Include="Yes" number="7">
					<cts source="AITAM" domain="07 Application Controls" area="02 Processing Controls" issue="02 Application controls"/>
					<quote type="description">The organization must ensure that all legal aspects are identified, addressed and configured in the information system.    Each tax liability for payment according to a tax return is three (3) euros or less, or any other small amount determined by the Director General, TAK will treat the tax payable as zero value.</quote>
					<!--<quote type="recommendation"/>-->
				</Case>
				<Case nr="F20200513-160806" nm="CCMS does not provide notifications in cases when the payment agreement is not respected" eff="The lack of a detailed report in the system about the taxpayers who have not complied with the payment deadline according to the payment schedule and non-termination of the agreement in such cases, results in taxpayers benefiting from deductions of sanctions (penalty for non-payment will be reduced to 2% of the tax base, while the interest remains payable) even though they have not met the terms of the agreement. This also results with the unequal treatment of taxpayers who have concluded payment agreement." act="" doc="" Include="Yes" number="8">
					<cts source="AITAM" domain="07 Application Controls" area="04 Application security controls" issue="01 Traceability mechanisms"/>
					<quote type="description">The organization needs to ensure that information systems support its goals and strategy.   If the agreement is up to 12 months, the calculation of interest will stop from the month following the month in which the agreement was signed. If the taxpayer meets the full agreement, he will be entitled to reduction of sanctions.</quote>
					<!--<quote type="recommendation"/>-->
				</Case>
				<Case nr="F20200513-161733" nm="SIGTAS system does not enable division of levels for taxpayer management by regions" eff="This system configuration error and unrestricted access of officials risks that taxpayer data is misused either intentionally or unintentionally, and that this data is accidentally altered/deleted by the officials who are not authorized to intervene." act="" doc="" Include="Yes" number="9">
					<cts source="AITAM" domain="05 Information  and Cyber Security" area="02 Security Policy" issue="01 Information Security Policy"/>
					<quote type="description">Confidentiality and integrity of records in the IT system must be protected by controlled access ensuring that only authorized employees have access to certain resources. </quote>
					<quote type="recommendation"/>
